### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by mstoykov** [avitalique/xk6-file#2]
Hi, I've noticed due to a [k6 community forum question](https://community.k6.io/t/unable-to-locate-xk6-after-installing-it/1866/6?u=mstoykov) that this repository doesn't use [semver](https://semver.org/). Unfortunately, go doesn't recognize anything that isn't in semver `vX.Y.Z` as a versioned tag so your v1.1 and v1.2 are not versions for go. Additionally, there is a cached v0.1.1 which means that `@latest` will use that.

Can you tag `v1.2` as `v1.2.0`, and preferably do the same for `v1.1` to `v1.1.0`.

Glad you made this extension and I hope you like using and developing for k6 ;)

**Comment by avitalique** [comment]
@MStoykov thank you for pointing this out to me. I have changed the tags according to semver.
