### ISSUE TITLE
how to delete a row using the xk6-file? is it supports? 

### ISSUE THREAD

**Issue by vsrn** [avitalique/xk6-file#3]
how to delete a row using the xk6-file? is it supports?

**Comment by avitalique** [comment]
@vsrn as for now, xk6-file doesn't support deleting strings from a file. Could you please describe your use case?

**Comment by avitalique** [comment]
Deleting a row has been added in release [v1.3.0](https://github.com/avitalique/xk6-file/releases/tag/v1.3.0)
