### ISSUE TITLE
k6 initiates one file per vu if filename is taken as a timestamp

### ISSUE THREAD

**Issue by forkintheass** [avitalique/xk6-file#6]
It seems like k6 will create one file per vu if filename initiated as a timestamp with milliseconds. Probably the problem is somewhere in between xk6-file and k6.

**Steps to reproduce:**
1. Initiate filepath with replacing ':' symbol
`const filepath = new Date().toISOString().replace(/:/g,'-') + '.csv';`
2. Set 5 users target in scenario, for example:
```js
export const options = {
  scenarios: {
    constant_request_rate: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { target: 5, duration: '5s' }, 
      ],
    },
  },
};
```
3. Set response time putting into the file, for example:
```js
  file.appendString(filepath, 
    response.timings.duration+"\n"
    );
```
4. Run

**Expected results:**
One file is initialised and is being written to, for example: 2023-03-13T16-20-26.007Z.csv

**Actual results:**
One file per each planned vu is created, each VU writes to its own file.
```bash
ubuntu@ip-172-26-0-112:~$ ls -alh *.csv
-rw-r--r-- 1 ubuntu ubuntu 18K Mar 13 17:19 2023-03-13T17-18-48.246Z.csv
-rw-r--r-- 1 ubuntu ubuntu 18K Mar 13 17:19 2023-03-13T17-18-48.248Z.csv
-rw-r--r-- 1 ubuntu ubuntu 18K Mar 13 17:19 2023-03-13T17-18-48.249Z.csv
-rw-r--r-- 1 ubuntu ubuntu 17K Mar 13 17:19 2023-03-13T17-18-48.250Z.csv
-rw-r--r-- 1 ubuntu ubuntu 17K Mar 13 17:19 2023-03-13T17-18-48.253Z.csv
```

**Technical details**
- Checked on Ubuntu 18.04 and Amazon Linux 2, result is the same.
- built with 
```xk6 build v0.43.1 --with github.com/avitalique/xk6-file```
and go 1.20
- This one seems to depend on speed of initialisation of vus. They all initialise at the start and upon initialising generate that filename by calling a method with system time/date request. If initialisation take milliseconds and seconds - time will be different. I believe there's nothing to fix on your side - not sure how can this be avoided by plugin.

**Workaround**
Cut milliseconds from the file name:
```js
const filepath = new Date().toISOString().replace(/[:.]/g,'-').slice(0,-5) + '.csv';
```

**Comment by grantquail-BO** [comment]
fwiw, the actual results you describe are indeed the expected results.  Every VU runs independently and has no knowledge of other VUs.   If you want all VUs to work on the same file, you need to set that filename somewhere in the `init` or `setup` portions of your script.

It is a coincidence that each of your VUs gets a timestamp during the same second, allowing them to select the same filename independently.  But if 1 of the VUs was delayed starting for some reason, or the starting of VUs happens to span the tick between seconds, they'd select different filenames.

**Comment by masoud-msk** [comment]
The correct way of handling this situation is to create `filepath` in the `setup` function so that K6 will execute it once per test, not in the `init` section (outside any function) which will be executed once per each VU.
```js
export function setup() {
  const filepath = new Date().toISOString().replace(/:/g,'-') + '.csv';
  return { filepath };
}

export default function ({ filepath }) {
  // ...
  file.appendString(
    filepath, 
    response.timings.duration+"\n",
  );
  // ...
}
```
Take note that it's not related to `xk6-file` extension.
