### ISSUE TITLE
Needed to maintain listing in k6 Extensions Registry

### ISSUE THREAD

**Issue by javaducky** [avitalique/xk6-file#7]
We've recently updated the requirements for maintaining an extension within the listing on our site. As such, please address the following items to maintain your listing within the registry:

* add an `examples` directory containing k6 test scripts making use of your extension
* needs to build with a recent version of k6; minimum v0.43

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

**Comment by avitalique** [comment]
Thank you for submitting this! All the mentioned points have been addressed in the latest release v1.3.0

**Comment by javaducky** [comment]
Thank you!
