### ISSUE TITLE
It would be useful if we could rename files

### ISSUE THREAD

**Issue by pietro-saccani** [avitalique/xk6-file#9]
Hello. My use case is that I have a file that is read from at the start of the script, and then re-written during tests.  
The problem is that in case of unexpected errors, the file remains incomplete and I lose the previous version of it, which could be re-used.  
If we could rename files, I would be able to write in a temporary file, and only at the end (in the teardown phase) delete the original file and replace it with the temporary one.  
This is needed only because we can't read files outside of the init phase, by the way. Otherwise I could read the temp file's contents and write them in the main file.  
  
Just a suggestion. It's not vital since in the end, unexpected, blocking errors shouldn't happen during tests.  
  
P.S. Another function that I found myself in need of would be to check the existence of a file. Unfortunately even using "open" in a try-catch will make the entire run fail if the file doesn't exist.

**Comment by avitalique** [comment]
Implemented. Thanks for your request.
